services:
  - type: web
    name: lost-gates-mvp
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: npm start
    branch: main
    publicDir: frontend/build  # This points to the 'build' folder after npm run build
    healthCheckPath: /  # Optional, specify a health check endpoint if you have one
