version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_REGION=us-east-1
    volumes:
      - .:/app
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
