services:
  - type: web
    name: lost-gates-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    plan: free
    autoscale: true
    envVars:
      - key: AWS_ACCESS_KEY_ID
        value: your_aws_access_key
      - key: AWS_SECRET_ACCESS_KEY
        value: your_aws_secret_key
